name: Build et sauvegarde de l'image Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # Only needed if pushing to GitHub Packages

    steps:
      - name: Récupération du code source
        uses: actions/checkout@v3

      - name: Construction de l'image Docker via docker-compose
        working-directory: ../../hands_on_microservices
        run: docker-compose build

      - name: Sauvegarder l'image Docker en fichier tar
        working-directory: ../../hands_on_microservices
        # Remplacez "mon_image:latest" par le nom et le tag de votre image tel que défini dans votre docker-compose.yml
        run: docker save -o mon_image.tar mon_image:latest

      - name: Upload de l'artefact (l'image Docker sauvegardée)
        uses: actions/upload-artifact@v3
        with:
          name: mon_image
          path: mon_image.tar
